### ISSUE TITLE
Feature req

### ISSUE THREAD

**Issue by niftyapple** [CodeCrafter47/BungeeMail#1]
Feature req for this plugin: Delete all mail older than X days globally. Possibly check for old email once daily or at user login? I could see some medium size servers getting massive databases of mail if people arent instructed to clean up their mailbox. Or maybe a limit to how many mails will be kept and remove the oldest one when the limit is met?

**Comment by AeSix** [comment]
So, I'm confused, because BungeeMail has a cleanup x-days old mail setting in the config.  Perhaps this has been added and the issue not properly handled?

**Comment by CodeCrafter47** [comment]
I think you are right. This has already been implemented.
